on:
  schedule:
    - cron: '15 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://intense-brushlands-70625.herokuapp.com/health
          max-attempts: 3 
          retry-delay: 5s

